### PR TITLE
Updated vg to version v1.4.0-1099-g9aa20df

### PR DESCRIPTION
**Pull request by cmarkello**
Added docker image removal in vg make clean target

Updated vg to version v1.4.0-1099-g9aa20df

### CODE REVIEW

**Comment by fnothaft** [comment]
How's this different from #164?

**Comment by cmarkello** [comment]
Sorry I messed up the rebase and somehow put my edits into an older commit. Trying to fix that now.

**Comment by cmarkello** [comment]
Jenkins, test this please

**Comment by cmarkello** [comment]
@fnothaft -- ready for review

**Comment by fnothaft** [comment]
LGTM! Merged. Thanks @cmarkello.

**Pull request merged**
