### PR TITLE
Spark nodes should have an attached local directory for shuffle files.

### PR DESCRIPTION
**Pull request by fnothaft**
See #68. This is similar, but for Spark.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Don't you also need to point the slaves at the /ephemeral/spark?

**Comment by fnothaft** [comment]
@hannes-ucsc correct, but I'll do that in a follow-on PR against toil-scripts. The configuration is a bit cleaner that way, IMO.

Hold on merging this until @almussel tests it.

**Comment by hannes-ucsc** [comment]
I meant to say: Don't you also want to configure the Spark slave daemon to use /ephemeral/spark for shuffle?

**Comment by hannes-ucsc** [comment]
I see.

**Comment by fnothaft** [comment]
Just opened the companion PR.

**Comment by fnothaft** [comment]
@hannes-ucsc what "needs work" from your side on this? I think it is good to go from mine.

**Comment by hannes-ucsc** [comment]
I set the flag based on your statement:

> Hold on merging this until @almussel tests it.

**Comment by fnothaft** [comment]
Thanks for the quick reply and merge @hannes-ucsc!

**Pull request merged**
