### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### BD2KGenomics/cgl-docker-lib now has a Chat Room on Gitter

@hannes-ucsc has just created a chat room. You can visit it here: [https://gitter.im/BD2KGenomics/cgl-docker-lib](https://gitter.im/BD2KGenomics/cgl-docker-lib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/BD2KGenomics/cgl-docker-lib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by heuermh** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Appears I don't have authority to kick Jenkins, can I just merge this?  Are there any contributing docs I should read first?

**Comment by fnothaft** [comment]
Ping @hannes-ucsc!

**Comment by benedictpaten** [comment]
Why is this in the backlog? @hannes-ucsc

**Pull request merged**
