### PR TITLE
Added CheckBias (resolves #91)

### LINKED ISSUE #91: Containerize: QC for Spladder run
https://github.com/KjongLehmann/m53

### PR DESCRIPTION
**Pull request by jvivian**
Added CheckBias

https://github.com/KjongLehmann/m53/commit/612f1296541cb76622d8f8b5df7d9072417bd3ac

### CODE REVIEW

**Comment by jvivian** [comment]
jenkins test this please.

**Comment by jvivian** [comment]
Thanks for waking up Jenkins, I know it's a Saturday.  Can you test this please?

**Comment by jvivian** [comment]
@hannes-ucsc Can you trigger a build for this PR?  If we're still refactoring CGL-docker-lib I'll just push it to my local repo as we discussed.

**Comment by hannes-ucsc** [comment]
A PR build won't push anything. I would have to merge this, and I would. If you think tests can be added easily, I would do that. The commit message should be 

```
Added CheckBias

https://github.com/KjongLehmann/m53/commit/612f1296541cb76622d8f8b5df7d9072417bd3ac
```

**Comment by hannes-ucsc** [comment]
You changed the PR title but I meant the commit message.

**Comment by jvivian** [comment]
> You changed the PR title but I meant the commit message.

@hannes-ucsc Sorry, sloppy on my part.

**Comment by jvivian** [comment]
@hannes-ucsc What needs to be done before this can be merged?

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/cgl-docker-lib/pull/92#issuecomment-194577231

**Comment by hannes-ucsc** [comment]
And please squash the two commits into one using the comment message I posted above.

**Comment by jvivian** [comment]
@hannes-ucsc Somehow my squash grew into 2 additional commits. At this point, if you won't merge it i'll just close it.

**Comment by hannes-ucsc** [comment]
Please squash all commits into one and force push.

**Comment by jvivian** [comment]
@hannes-ucsc Squashed and rebased to master.

**Pull request merged**
