### PR TITLE
Adding Dockerfile and Makefile for apache-spark version 1.5.0 (resolves #12)

### LINKED ISSUE #12: “Hello World” on Spark containers
Set up small Spark cluster using containers + toil
Download file from S3 to cluster, upload file back from cluster to S3

### PR DESCRIPTION
**Pull request by heuermh**
Progress towards #12.

A few questions in advance:
- is it ok to keep John as maintainer?
- has anyone figured out the proper way to hit the Apache download closer script with curl?
- is `tgz` appropriate for srcType in the tag name?
- will apache-spark require a wrapper script?

### CODE REVIEW

**Comment by fnothaft** [comment]
> is it ok to keep John as maintainer?

I would list you as the maintainer for now.

> has anyone figured out the proper way to hit the Apache download closer script with curl?

I normally just wget from Apache. What problems are you having?

**Comment by heuermh** [comment]
> I normally just wget from Apache. What problems are you having?

Hitting this download link with curl doesn't work for me; it returns text/html, not gzip
http://www.apache.org/dyn/closer.lua/spark/spark-1.5.0/spark-1.5.0-bin-hadoop2.6.tgz

...so I don't know how this is supposed to work
https://github.com/apache/spark/blob/master/docker/spark-mesos/Dockerfile#L27

**Comment by fnothaft** [comment]
Where did you get that link from? I think this is partially an issue on the Apache side. If you select the "Select Mirror" link when downloading Spark, the link gives you the page listing all mirrors, not a link that redirects to the "best" mirror. I usually use their "Direct Download" link.

**Comment by hannes-ucsc** [comment]
https://github.com/BD2KGenomics/cgcloud/blob/master/spark/src/cgcloud/spark/spark_box.py#L418

**Comment by hannes-ucsc** [comment]
And yes, Michael should be the maintainer of this Dockerfile.

**Comment by heuermh** [comment]
Right, the direct download link is dynamic, so we can either add some script as in `spark_box.py` or arbitrarily choose one of the mirrors, which this pull request does.

**Comment by hannes-ucsc** [comment]
Right, I'd prefer the former.

**Comment by heuermh** [comment]
ok, that somewhat exceeds my experience with docker.

Would you suggest refactoring some code from `spark_box.py` into a new python script/library and then including it in the docker image via the file system when building the image?  Or download such from the network?

**Comment by hannes-ucsc** [comment]
Would this work?

```
RUN path="spark/spark-1.2.1/spark-1.2.1-bin-hadoop2.4.tgz" ; curl `python -c "from urllib2 import urlopen; import json; print json.load( urlopen('http://www.apache.org/dyn/closer.cgi?path=$path&asjson=1'))['preferred']"`/$path | tar --strip-components=1 -xzC /opt/apache-spark
```

**Comment by hannes-ucsc** [comment]
Mentioning the ticket in the subject line cause Waffle to stack PR and issue.

**Comment by hannes-ucsc** [comment]
Don't we need Hadoop as well? And the entry points should start the Spark and HDFS daemons instead of spark-submit, right?

**Comment by heuermh** [comment]
> Mentioning the ticket in the subject line cause Waffle to stack PR and issue.

I didn't do that because this pull request doesn't actually resolve #12, only makes progress towards it.  What is Waffle?

**Comment by hannes-ucsc** [comment]
https://waffle.io/BD2KGenomics/toil

Unless there is a good reason not to, we only merge PRs that solve an issue.  IOW, when this PR is ready to be merged, it will resolve #12.

**Comment by heuermh** [comment]
I see.  Thank you for the clarification.

**Comment by hannes-ucsc** [comment]
Superseded by #29

**Pull request closed without merging**
