### PR TITLE
remove spark and scala version scripts for Mango

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by akmorrow13** [comment]
@fnothaft @jvivian could you review?

**Comment by jvivian** [comment]
@akmorrow13 — Sorry for the delay, I'll take a look after the build finishes

**Comment by akmorrow13** [comment]
thanks @jvivian. I think someone needs to review the PR before it is built

**Comment by jvivian** [comment]
@akmorrow13 — Ah, my apologies. I have a meeting for the next hour but then I can take a look.

**Review by jvivian — APPROVED** [review]

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by jvivian** [comment]
@akmorrow13 — I tried a manual build last night and the server says it's offline. I'd just merge administratively, but I'm not sure it would run the build that pushes to quay.  I'm going to message the person who runs our CI server and ask what's up.

**Comment by jvivian** [comment]
@akmorrow13 — He just got back to me, "The worker images are out of date due to Jenkins upgrades. I will take a look at it."

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by akmorrow13** [comment]
thanks for looking into this @jvivian!

**Comment by akmorrow13** [comment]
thanks @jvivian !

**Pull request merged**
