### PR TITLE
ADAM recompute updates (resolves #201)

### LINKED ISSUE #201: Misc upgrades for ADAM recompute
- [ ] Move to Spark 2.1.0
- [ ] Update to ADAM 0.22.0
- [ ] Bring back bwa container
- [ ] Add Spark+BWA container
- [ ] Add avocado container
- [ ] Add cannoli container

Tools to benchmark against:
- [ ] FreeBayes
- [ ] Platypus
- [ ] 16GT
- [ ] Strelka2
- [ ] GATK4
- [ ] mpileup (part of samtools, need to add bcftools)

Tools to use in benchmarking evaluation:
- [ ] hap.py

### PR DESCRIPTION
**Pull request by fnothaft**
WIP:

- [x] Move to Spark 2.1.0
- [x] Update to ADAM 0.22.0
- [x] Bring back bwa container
- [x] Add Spark+BWA container
- [x] Add avocado container
- [x] Add cannoli container
- [x] Upgrade conductor container to Spark 2 (https://github.com/BD2KGenomics/conductor/issues/19)

Tools to benchmark against:
- [x] FreeBayes
- [x] Platypus
- [x] 16GT
- [x] Strelka2
- [x] GATK4
- [x] mpileup (part of samtools, need to add bcftools)

Tools to use in benchmarking evaluation:
- [x] ~hap.py~ image exists at https://hub.docker.com/r/pkrusche/hap.py/tags/

### CODE REVIEW

**Comment by fnothaft** [comment]
@cket WRT Jenkins, it looks like something is hung up here.

**Comment by cket** [comment]
Jenkins, test this please

**Comment by fnothaft** [comment]
@jvivian I believe this is good to go from my side. Can you review/merge?

**Review by jvivian — APPROVED** [review]
Looks good, thanks for handling some of the tools' version bumps.

**Comment by fnothaft** [comment]
Thanks @jvivian!

**Pull request merged**
