### PR TITLE
updated Gencode v23 to v24 for bamQC

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by akmorrow13** [comment]
Fixes https://github.com/BD2KGenomics/cgl-docker-lib/issues/286 and https://github.com/BD2KGenomics/cgl-docker-lib/issues/287

**Comment by akmorrow13** [comment]
@jvivian can you review?

**Comment by jvivian** [comment]
@akmorrow13 -- I appreciate you updating this, but the BamQC container is part of the toil-rnaseq workflow that's based on V23, so I'll need to find a replacement BED for V23 to resolve this. I'm asking the bamQC author if she has a copy somewhere.

**Comment by akmorrow13** [comment]
Ah ok makes sense! I can close this or you can just update me on the location of the file and I can update the PR, whatever you prefer

**Comment by akmorrow13** [comment]
@jvivian is there  a sample file laying around for the v23 version that we can use to find online? We can possibly use mysql to pull the v23 data, but we need to know the column order to do that

**Comment by jvivian** [comment]
@akmorrow13 — Sorry for the delay. If you want to update the PR, here's a new link for the bedfile: http://courtyard.gi.ucsc.edu/~jvivian/bamqc/hg38_GENCODE_v23.bed.gz

**Comment by akmorrow13** [comment]
Thanks for posting the file @jvivian ! I have updated the PR.

**Review by jvivian — APPROVED** [review]

**Pull request merged**
