### PR TITLE
Docker pipelines for exome var, bwa alignment

### LINKED ISSUE #128: Containerize exome pipeline

### PR DESCRIPTION
**Pull request by alex-hancock**
Resolves #128, #129

### CODE REVIEW

**Comment by jvivian** [comment]
I do not have merge privileges. LGTM.

**Comment by hannes-ucsc** [comment]
> I do not have merge privileges. LGTM.

You should now.

**Comment by hannes-ucsc** [comment]
-1 for now

Does this have tests?

**Comment by jvivian** [comment]
@alex-hancock - Adding tests should be easy, just look at any of the other docker directories for an example. The tests aren't really useful at the moment, as they just check if executing the container returns a non-zero exit code, but once we move the container code to the separate pipeline repositories we'll have a chance to make them more comprehensive.

**Comment by jvivian** [comment]
@alex-hancock — Since apparently these are already being pushed to quay despite lack of review, is there a hard deadline on this PR?

**Comment by jvivian** [comment]
I'll have to figure out why the jenkins build failed considering you didn't touch any files outside the two new directories you're creating.

**Comment by jvivian** [comment]
I'll have to file a PR to fix why jenkins is breaking, tracking that in #184

**Comment by Jeltje** [comment]
Both images need documentation similar to [that of the rnaseq-cgl-pipeline](https://github.com/BD2KGenomics/cgl-docker-lib/tree/master/rnaseq-cgl-pipeline)

Then update the usage statement on the image itself (`bwa-alignment-cgl-pipeline` currently refers to [the pip installable version](https://github.com/BD2KGenomics/toil-scripts/tree/master/src/toil_scripts/bwa_alignment))

Also make sure the usage statement matches the image ID. Currently
`docker run quay.io/ucsc_cgl/bwa-alignment-cgl-pipeline:2.0.8--1.9.1--`
gives
`docker run -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock quay.io/ucsc_cgl/bwa-alignment --samples sample1.tar`
(note it refers to `bwa-alignment` instead of  `bwa-alignment-cgl-pipeline`)

**Comment by hannes-ucsc** [comment]
Alex, be sure to address @Jeltje's comments.

And please rename the containers to toil-bwa-alignment and toil-exome-variant, respectively.

FYI: https://github.com/BD2KGenomics/toil-rnaseq/issues/12

**Comment by jvivian** [comment]
Stale and unneeded, closing.

**Pull request closed without merging**
