### PR TITLE
Log failed tools in jenkins.py and exit if a build failed (resolves #211)

### LINKED ISSUE #211: Fix jenkins.py so that failing builds fail the build
See discussion in #207, specifically https://github.com/BD2KGenomics/cgl-docker-lib/issues/207#issuecomment-265900092 and https://github.com/BD2KGenomics/cgl-docker-lib/issues/207#issuecomment-265935186

### PR DESCRIPTION
**Pull request by fnothaft**
Adds logic to the `run_make` step in jenkins.py that tracks all build stages that have failed. At the end, if one or more command failed, then all failed commands are printed, and we exit with a non-zero exit code, which will cause Jenkins to mark the build as failed. As opposed to throwing an exception whenever a command fails, this approach allows us to run through all of the builds, which is preferable from a debugging perspective.

### CODE REVIEW

**Review by hannes-ucsc — APPROVED** [review]

**Comment by cket** [comment]
Looks good. Just double checking, the build/push process for each tool is independent right? An error in one tool won't stop another tool from successfully pushing to quay?

**Comment by fnothaft** [comment]
Before this merges, we should fix the following:

```
ERROR:__main__:Tool adam-pipeline, command ['make']
ERROR:__main__:Tool apache-spark-master, command ['make']
ERROR:__main__:Tool vg, command ['make']
ERROR:__main__:Tool rnaseq-cgl-pipeline, command ['make']
ERROR:__main__:Tool apache-spark-worker, command ['make']
ERROR:__main__:Tool apache-spark-common, command ['make']
ERROR:__main__:Tool adam-pipeline, command ['make', 'test']
ERROR:__main__:Tool apache-spark-master, command ['make', 'test']
ERROR:__main__:Tool vg, command ['make', 'test']
ERROR:__main__:Tool rnaseq-cgl-pipeline, command ['make', 'test']
ERROR:__main__:Tool adam, command ['make', 'test']
ERROR:__main__:Tool apache-spark-worker, command ['make', 'test']
ERROR:__main__:Tool apache-spark-common, command ['make', 'test']
```

I can take anything with `adam` or `spark` in the name. @jvivian can you look at `rnaseq-cgl-pipeline`? @cmarkello can you look at `vg`?

> Looks good. Just double checking, the build/push process for each tool is independent right? An error in one tool won't stop another tool from successfully pushing to quay?

Correct!

**Comment by fnothaft** [comment]
Also, from the perspective of build log spamming, we shouldn't build later steps of the build for a tool if an earlier phase fails. E.g., if `make` fails, we shouldn't run `make test`.

**Comment by cket** [comment]
@fnothaft @jvivian I'll take the RNA-seq failures

**Comment by fnothaft** [comment]
Hi @cket just wanted to ping this PR and see if you were ready to merge it. I just came across an issue in #241 that I think this PR would have caught that the current CI doesn't catch.

**Comment by cket** [comment]
@fnothaft yeah, sorry this fell of the radar. I just want to check if the test fixes were ever implemented. Jenkins, test this please

**Comment by cket** [comment]
@fnothaft the build is still failing with the same errors as above. I can fix the rna-seq failures just by removing it from the repo since the docker pipeline is now in the toil-rnaseq repo.

**Comment by fnothaft** [comment]
@cket SGTM; I can delete the two RNA-seq containers that are failing, and I'll take a hack at the Spark containers.

**Comment by cket** [comment]
I just deleted them, I'm also looking at fixing VG and kallisto_sc which I just noticed is also failing `make` and `make test`.

**Comment by fnothaft** [comment]
Thanks @cket!

**Comment by jvivian** [comment]
Late to checking in on this sorry. Thanks @fnothaft @cket.

**Comment by cket** [comment]
@fnothaft can you rebase the PR on master? I'm ready to open the build/test fix PR that includes changes to kallisto_sc but that project isn't on this branch yet

**Comment by fnothaft** [comment]
@cket Rebased!

**Comment by cket** [comment]
9 failures now, made some progress!
```
ERROR:__main__:Tool adam-pipeline, command ['make']
ERROR:__main__:Tool apache-spark-master, command ['make']
ERROR:__main__:Tool apache-spark-worker, command ['make']
ERROR:__main__:Tool apache-spark-common, command ['make']
ERROR:__main__:Tool adam-pipeline, command ['make', 'test']
ERROR:__main__:Tool apache-spark-master, command ['make', 'test']
ERROR:__main__:Tool adam, command ['make', 'test']
ERROR:__main__:Tool apache-spark-worker, command ['make', 'test']
ERROR:__main__:Tool apache-spark-common, command ['make', 'test']
```

**Comment by fnothaft** [comment]
Yup! I'm working on those last few errors right now. Thanks for the help, CJ!

**Comment by fnothaft** [comment]
OK, should have the remaining issues fixed. Tests are running right now.

**Comment by fnothaft** [comment]
I'm just going to tack two more commits on, actually.

**Comment by fnothaft** [comment]
@cket @jvivian this is good to merge from my end!

**Review by cket — APPROVED** [review]
LGTM, thanks @fnothaft!

**Comment by fnothaft** [comment]
@jvivian can you review this? I will clean up history if it is good on your end.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Review by jvivian — APPROVED** [review]
Thanks for the touch-ups in some of the other tools!

**Pull request merged**
