### PR TITLE
Adding glenn2vcf

### PR DESCRIPTION
**Pull request by cmarkello**
Commit history is a mess due to attempts at editing previous commit labels and rebasing issues pulling in history from other branches.

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
It's not going to go in like that. Sorry. Learn how to interactively rebase and how to squash with git. I can highly recommend Atlassian's SourceTree.

This needs to be one commit with a proper 72 character title (first line of the commit message).

**Comment by jvivian** [comment]
@cmarkello — I'm leaving town tomorrow for a wedding, but if this isn't urgent I can help you with this early next week.

**Comment by cmarkello** [comment]
@jvivian -- It's not urgent. Just frustrating doing history editing in git. I'll try and see if I can use sourceTree to do the editing properly.

**Comment by jvivian** [comment]
Definitely, it just takes seeing someone do it a couple times to understand
(in my case at least).

**Comment by hannes-ucsc** [comment]
@cmarkello, we allow force-pushing to PR branches. There is no need to close and open a new PR every time you alter the Git history.

**Pull request closed without merging**
