### PR TITLE
Updating Apache Spark version to 1.5.2

### LINKED ISSUE #57: Bump Apache Spark version to 1.5.2

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #57

### CODE REVIEW

**Comment by fnothaft** [comment]
@heuermh can you update this in the adam dockerfile as well?

**Comment by heuermh** [comment]
Thanks, missed the one in `adam/build/download.sh`

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Thanks!

**Pull request merged**
