### PR TITLE
Broke build in bwa-kit by forgetting to update one nametag.

### PR DESCRIPTION
**Pull request by fnothaft**
@hannes-ucsc sorry, I did a stupid.

### CODE REVIEW

**Comment by fnothaft** [comment]
Thanks @hannes-ucsc ! Testing this now.

**Comment by hannes-ucsc** [comment]
The Jenkins build that pushes to quay.io is still underway ...

http://jenkins.cgcloud.info/job/cgl-docker-lib/99/

**Comment by fnothaft** [comment]
Indeed; we couldn't find the image and thus the job failed... Rerunning now.

**Comment by hannes-ucsc** [comment]
0.7.12--f05007590c9e2953d20a0a18aa412454eed3ab59
http://jenkins.cgcloud.info/job/cgl-docker-lib/99/
https://quay.io/repository/ucsc_cgl/bwakit?tab=tags

**Pull request merged**
