### PR TITLE
Delete unused containers (resolves #173)

### LINKED ISSUE #173: Delete unused containers
This was bothering me.
- bwa (replaced by bwakit)
- dupe containers:
  - mapsplice-2.0.1.9
  - rsem-1.1.13
  - samtools-1.3
  - ubu-1.0

@jvivian I grepped through toil-scripts and didn't see any of these, so I assume they're good to remove:

```
fnothaft$ grep samtools-1.3 -R src/
fnothaft$ grep rsem-1.1.1.3 -R src/
fnothaft$ grep rsem-1.1.13 -R src/
fnothaft$ grep mapsplice-2.0 -R src/
fnothaft$ grep ubu-1.0 -R src/
fnothaft$ pwd
/Users/fnothaft/IdeaProjects/toil-scripts
```

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #173

### CODE REVIEW

**Comment by hannes-ucsc** [comment]
What's the motivation for this? Shouldn't we be able to recreate those old images in case, say, quay.io goes up in smoke?

**Comment by hannes-ucsc** [comment]
Ignore my question.

**Comment by fnothaft** [comment]
I mean, if we wanted to do that, we could do that by going back to the tagged release (oh wait, we don't have one) where those containers existed. That being said, the containers are unused in the toil-scripts pipelines.

**Comment by hannes-ucsc** [comment]
Do you want to discuss here or on the issue?

**Comment by fnothaft** [comment]
I'd prefer on the issue.

**Comment by fnothaft** [comment]
Just pushed a revised branch that breaks the deletions out into separate commits and undoes the deletion of `quay.io/ucsc_cgl/samtools:1.3--*`. Ping @jvivian for review.

**Comment by jvivian** [comment]
mmm -350 lines.  LG2M!

**Comment by fnothaft** [comment]
Rebased. Ping for merge.

**Review by hannes-ucsc — APPROVED** [review]

**Pull request merged**
