### PR TITLE
Update ADAM container commit version

### PR DESCRIPTION
**Pull request by fnothaft**
Lock ADAM docker container to https://github.com/bigdatagenomics/adam/commit/cd6ef4162ae97460059ef067d21bbed7e060b289 which is https://github.com/bigdatagenomics/adam/pull/921.

### CODE REVIEW

**Comment by heuermh** [comment]
tests ok for me

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by hannes-ucsc** [comment]
Is this still needed?

**Comment by fnothaft** [comment]
Yes-I didn't realize it had merge conflicts. I will resolve those tomorrow.

**Comment by fnothaft** [comment]
@hannes-ucsc merge conflicts are fixed; please merge.

**Comment by heuermh** [comment]
In order to build this after merge, I had to use `docker build --no-cache ...`.

The build fails with

``` bash
$ make
...
Step 6 : RUN git checkout cd6ef4162ae97460059ef067d21bbed7e060b289
 ---> Running in 4a0f271a4f96
Note: checking out 'cd6ef4162ae97460059ef067d21bbed7e060b289'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at cd6ef41... Merge pull request #921 from fnothaft/project-out-tags
 ---> 4d2f091ca585
Removing intermediate container 4a0f271a4f96
Step 7 : RUN /opt/apache-maven-3.3.3/bin/mvn package -DskipTests
 ---> Running in 97d43876f86e
...
 ---> 15c7fe79fe27
Removing intermediate container 97d43876f86e
Successfully built 15c7fe79fe27
echo /Users/heuermh/working/cgl-docker-lib/adam/runtime
/Users/heuermh/working/cgl-docker-lib/adam/runtime
docker run -v /Users/heuermh/working/cgl-docker-lib/adam/runtime:/data quay.io/ucsc_cgl/adam:cd6ef41-build cp -r /home/adam /data/adam
cp: cannot create symbolic link '/data/adam/adam/adam-apis/src/test/resources/small.sam': Protocol error
cp: cannot create symbolic link '/data/adam/adam/adam-cli/src/test/resources/ordered.sam': Protocol error
cp: cannot create symbolic link '/data/adam/adam/adam-cli/src/test/resources/unordered.sam': Protocol error
make: *** [runtime/adam] Error 1
```

I believe I've seen this before but don't remember how we resolved it.  Would it be worth replacing the linked test resources in adam with copies instead?

**Comment by hannes-ucsc** [comment]
Is a virtualbox involved? I've seen mention of this error in relation to the shared host file system that virtualbox uses.

**Comment by heuermh** [comment]
Yup, on OSX docker-machine uses virtualbox, or at least that is how I'm using it.  I think you're right, that it is a problem with symbolic links on virtualbox fs.

In any case, should be solved by https://github.com/bigdatagenomics/adam/pull/927

**Pull request merged**
