### PR TITLE
Update Mango to Spark 2.4.3

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by jvivian** [comment]
Hi @akmorrow13 — Do you have write/merge privileges to this repo? I defended in early June and will not be a reliable PR master for this repo any longer.

**Comment by akmorrow13** [comment]
Congrats @jvivian! I do not believe I have merge/write privileges It says a review is required from reviewers with write access, and I am not authorized to merge this PR.

**Comment by jvivian** [comment]
@akmorrow13 — Thank you! It went well. I have permissions to grant you write privileges, just need Benedict to sign off.

If this is time sensitive let me know and I'll go ahead and merge.

**Comment by akmorrow13** [comment]
Thanks @jvivian! It should be fine for the next couple days.

**Comment by akmorrow13** [comment]
@jvivian it still says that a review is required by a reviewer with write access. Is there anyone else I can request a review from that is active?

**Comment by jvivian** [comment]
Hi @akmorrow13 — I didn't realize write access wouldn't give you permissions to push without review. I just added you via an option to, "Specify people or teams allowed to dismiss pull request reviews." Let me know if that changes anything.

**Comment by akmorrow13** [comment]
Thanks @jvivian. I still don't think I have the right access. I still see the following:
Screen Shot 2019-07-03 at 1 09 51 PM

It states at the bottom that I am not authorized.

**Review by jvivian — APPROVED** [review]

**Comment by jvivian** [comment]
Hi @akmorrow13 — I went ahead and approved. I also removed the requirement that status checks pass given the deprecation of Jenkins, so ideally next time you can just dismiss the review and will have the authority to merge.

**Comment by akmorrow13** [comment]
Thanks @jvivian. Does this mean no more build triggers? It still says I am not authorized to merge this pull request (it also says this on PR https://github.com/BD2KGenomics/cgl-docker-lib/pull/291 so I believe I am still missing the correct permissions)

**Comment by jvivian** [comment]
I've checked and you have "write" privileges to the repo so I'm not quite sure why only I'm authorized to merge. Will keep looking, in the mean time I merged.

**Comment by akmorrow13** [comment]
Thanks @jvivian ! Let me know if there is something on my end I have to do.

**Comment by jvivian** [comment]
I think I fixed it — push privileges was under a separate category for this "protected branch." Hopefully that resolves it, otherwise just ping me.

**Comment by akmorrow13** [comment]
@jvivian how was the quay.io build triggered? Does someone have to manually do that? If, so I could take that on in the future I just need the instructions.

**Comment by jvivian-atreca** [comment]
@akmorrow13 — I checked the tags and it wasn't pushed to Quay (which makes sense given that there's no associated Jenkins build anymore).

We could try and get this repo onto Travis CI, or an easier option might be to just use this repo for version control and push the containers you care about to your personal Dockerhub. Unfortunately, I don't think anyone in the CGL is actively using, maintaining, or contributing to this repo.

**Comment by jvivian** [comment]
@akmorrow13 — I checked the tags and it wasn't pushed to Quay (which makes sense given that there's no associated Jenkins build anymore).

We could try and get this repo onto Travis CI, or an easier option might be to just use this repo for version control and push the containers you care about to your personal Dockerhub. Unfortunately, I don't think anyone in the CGL is actively using, maintaining, or contributing to this repo.

**Comment by akmorrow13** [comment]
Thanks @jvivian. Is there anyway I could use the .dockercfg file to push one last time? I can move the project to a new quay repository in the future. However, I just cut a release that depends on the quay.io cgl Mango path. This way I could just 'make push' the Mango project.

**Comment by jvivian** [comment]
I'm trying to get it up on quay now, will keep you posted.

**Comment by akmorrow13** [comment]
Thank you so much @jvivian, I owe you all the beers.

**Comment by jvivian** [comment]
No problem! :beers: https://quay.io/repository/ucsc_cgl/mango?tab=tags

**Comment by akmorrow13** [comment]
Thanks so much @jvivian!

**Pull request merged**
