### PR TITLE
Add cmake (resolves #254)

### LINKED ISSUE #254: Make CMAKE base image

### PR DESCRIPTION
**Pull request by jvivian**
I added a `shorttag` to make the `FROM` line in the Dockerfile more palatable since this will be used as a base image.

### CODE REVIEW

**Comment by jvivian** [comment]
@fnothaft — ready for review.

**Comment by fnothaft** [comment]
Will do @jvivian; have a proposal submission today, will get to this tonight.

**Comment by jvivian** [comment]
@fnothaft — No rush, not a blocker currently.

**Review by fnothaft — APPROVED** [review]

**Comment by fnothaft** [comment]
Merged. Thanks @jvivian!

**Pull request merged**
