### PR TITLE
Add push target to all ADAM/Spark containers.

### PR DESCRIPTION
**Pull request by fnothaft**
Also adds a unit test for the ADAM container.

### CODE REVIEW

**Comment by jvivian** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Do you need the spark-and-maven one too?  Used as FROM [here](https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/adam/build/Dockerfile#L1)

**Comment by fnothaft** [comment]
Ah @heuermh you're right. I may have broken some things in a way that builds OK on machines that have prior versions of the images on them. Tagging this `needs work`, I will fix this PM.

**Comment by fnothaft** [comment]
Fixed.

**Pull request merged**
