### PR TITLE
updated Mango for Spark 2.3.2

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by akmorrow13** [comment]
@jvivian or @fnothaft can you trigger tests for this?

**Comment by jvivian** [comment]
jenkins, test this please.

**Comment by akmorrow13** [comment]
Requires https://github.com/BD2KGenomics/cgl-docker-lib/pull/288 for Jenkins tests to pass.

**Comment by akmorrow13** [comment]
@jvivian do we need to wait on https://github.com/BD2KGenomics/cgl-docker-lib/issues/286 to be fixed to merge in this PR?

**Comment by jvivian** [comment]
@akmorrow13 — Let's merge #288 and see if that fixes the builds. I'd just admin-merge this PR to prevent you from being blocked, but if the PR-merge fails to build on jenkins I worry that it won't reach the step where it would push this container to quay.io.

**Comment by jvivian** [comment]
@akmorrow13 — Do you need to update from master now that #288 is in, or do I just need to trigger the build?

**Comment by akmorrow13** [comment]
@jvivian I just rebased so you can trigger the build

**Comment by jvivian** [comment]
Jenkins, test this please.

**Review by jvivian — APPROVED** [review]

**Pull request merged**
