### PR TITLE
Fix submodule build in vg image. Updated vg to v1.4.0-1744-gea8edfd

### PR DESCRIPTION
**Pull request by cmarkello**

### CODE REVIEW

**Comment by fnothaft** [comment]
Is this needed to fix #207?

**Comment by cmarkello** [comment]
@fnothaft Yes this is needed to fix #207

**Review by fnothaft — APPROVED** [review]

**Comment by fnothaft** [comment]
Build log looks good.

**Comment by fnothaft** [comment]
Merged! Thanks @cmarkello !

**Pull request merged**
