### PR TITLE
Bump Java version in hadoop-common

### PR DESCRIPTION
**Pull request by almussel**

### CODE REVIEW

**Review by hannes-ucsc — APPROVED** [review]
+1, assuming that this is righting a wrong from an earlier commit.

**Comment by hannes-ucsc** [comment]
Depends on #184/#185 to fix the build before it can be merged.

**Comment by fnothaft** [comment]
+1

**Comment by hannes-ucsc** [comment]
Jenkins, test this please.

**Comment by almussel** [comment]
@hannes-ucsc this is passing now

**Pull request merged**
